"""Generates game_flow.rpy that handles map navigation and entry points.

This module creates the game_flow.rpy file providing the top-level navigation
structure for the Ren'Py game. It defines entry points for each map and
connects them via jump statements.

Navigation Architecture:
Ren'Py visual novels typically use labels for scene/location transitions:
    label start:
        jump map_1_enter

    label map_1_enter:
        call map_1_events
        return

This module generates this structure automatically from the collected map data.

Map Entry Labels:
Each map gets two labels:
1. map_{id}_enter: Entry point called from game_flow or transfers
2. map_{id}_events: Defined in the map's .rpy file, contains actual events

The separation allows for pre-entry logic (e.g., checking conditions) to be
added to the _enter label without modifying the events file.

Transfer Handling:
When the generator encounters a TRANSFER_PLAYER command, it emits:
    jump map_{target_id}_enter

This navigates to the target map's entry label, creating a seamless flow.

Output File Structure:
    # ═══════════════════════════════════════════════════
    # GAME FLOW — Map Navigation
    # Auto-generated from RPG Maker MV
    # ═══════════════════════════════════════════════════

    label start:
        # Change this to your starting map
        # jump map_1_enter  # Town Square
        # jump map_2_enter  # Forest Path
        jump map_1_enter  # Default: first map

    label map_1_enter:
        # Town Square
        call map_1_events
        return

    label map_2_enter:
        # Forest Path
        call map_2_events
        return
"""

from .collector import DataCollector


def generate_game_flow_rpy(
    all_map_data: dict[int, dict],
    collector: DataCollector,
) -> str:
    """Generate game_flow.rpy that handles map navigation and entry points.

    Creates a .rpy file with:
    - A `start` label that jumps to the first map (configurable)
    - A `map_{id}_enter` label for each map that calls its event handler

    This provides the top-level navigation structure for the Ren'Py game.
    Players navigate between maps via TRANSFER_PLAYER commands, which are
    translated to jump statements.

    Start Label:
    The `start` label is Ren'Py's entry point. By default, it jumps to map_1.
    The generated file includes commented-out alternatives for easy configuration:
        label start:
            # Change this to your starting map
            # jump map_1_enter  # Town Square
            # jump map_2_enter  # Forest Path
            jump map_1_enter  # Default

    Map Entry Labels:
    Each map gets an entry label that:
    1. Shows the map's display name in a comment
    2. Calls the map's events label (defined in map_{id}_events.rpy)
    3. Returns to the caller

    Args:
        all_map_data: Maps map_id → parsed JSON data for each transpiled map.
            Used to get display names for comments.
        collector: DataCollector instance with map name metadata.
            Used to retrieve display names for map IDs.

    Returns:
        Complete .rpy source string for game_flow.rpy.
        Ready to be written to a file.

    Example:
        >>> all_map_data = {1: map1_json, 2: map2_json}
        >>> collector = DataCollector()
        >>> # ... populate collector ...
        >>> source = generate_game_flow_rpy(all_map_data, collector)
        >>> with open("game_flow.rpy", "w") as f:
        ...     f.write(source)

    Note:
        The generated file assumes map event files (map_{id}_*.rpy) exist.
        These are generated by RenPyGenerator in parallel with this file.

    Note:
        The default starting map is map_1. Game designers should edit
        the start label to change the initial map.
    """
    # Initialize the output lines list
    output_lines: list[str] = []

    # ── File Header ──
    # Emit a decorative header with section marker
    output_lines.append("# ═══════════════════════════════════════════════════")
    output_lines.append("# GAME FLOW — Map Navigation")
    output_lines.append("# Auto-generated from RPG Maker MV")
    output_lines.append("# ═══════════════════════════════════════════════════")
    output_lines.append("")

    # ── Start Label ──
    # The start label is Ren'Py's entry point for the game
    output_lines.append("label start:")
    
    # Add an instruction comment for game designers
    output_lines.append("    # Change this to your starting map")
    
    # List all available maps as commented-out alternatives
    # This makes it easy for designers to change the starting map
    for map_id in sorted(all_map_data.keys()):
        # Get the map's display name for the comment
        map_name = all_map_data[map_id].get("display_name", f"Map {map_id}")
        # Emit the commented-out jump statement with map name
        output_lines.append(f"    # jump map_{map_id}_enter  # {map_name}")
    
    # Emit the default jump to map_1
    # Most games start at the first map
    output_lines.append("    jump map_1_enter")
    
    # Add blank lines for separation
    output_lines.append("")
    output_lines.append("")

    # ── Map Entry Labels ──
    # Generate an entry label for each map
    for map_id, map_data in sorted(all_map_data.items()):
        # Get the map's display name
        map_name = map_data.get("display_name", f"Map {map_id}")
        
        # Emit the map entry label
        output_lines.append(f"label map_{map_id}_enter:")
        
        # Emit a comment showing the map's display name
        output_lines.append(f"    # {map_name}")
        
        # Emit the call to the map's events label
        # The events label is defined in the map's .rpy file (generated by RenPyGenerator)
        output_lines.append(f"    call map_{map_id}_events")
        
        # Emit the return statement
        output_lines.append("    return")
        
        # Add a blank line for readability
        output_lines.append("")

    # Join all lines with newlines and return
    return "\n".join(output_lines)
